(* DO NOT EDIT THIS FILE *)
open Todolist

module type TodoSig = sig
  type todo
  type datatable

  val delete : string -> int -> datatable -> datatable
  val datatable_to_json : string -> datatable -> unit
  val add : string -> todo -> datatable
end

module TodoCheck : TodoSig = Todo
